engines:
  rubocop:
    enabled: true
    checks:
        Rubocop/Metrics/CyclomaticComplexity:
          enabled: true
        Rubocop/Metrics/ParameterLists:
          enabled: true
        Rubocop/Cop/TooManyLines:
          enabled: true
        Rubocop/Metrics/ClassLength:
          enabled: true
  eslint:
    enabled: true
    config:
      ignore_warnings: true
    checks:
      complexity:
        enabled: true
      max-depth:
        enabled: true
      max-params:
        enabled: true
      max-lines:
        enabled: true
      block-spacing: 
        enabled: false
      brace-style: 
        enabled: false
      comma-dangle: 
       enabled: false 
      comma-style: 
        enabled: false
      complexity: 
        enabled: false
      curly:
        enabled: false
      eqeqeq: 
        enabled: false
      no-shadow-restricted-names:
        enabled: false
      no-undef:
        enabled: false
      no-use-before-define:
        enabled: false
      radix: 
        enabled: false
      semi: 
        enabled: false
      space-infix-ops:
        enabled: false
      strict: 
        enabled: false
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  golint:
    enabled: false
  gofmt:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      - javascript:

ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
   - "**.go"
   - "**.js"

exclude_paths:
  - spec/**/*
  - vendor/**/*
